### ISSUE TITLE
WA2AD appears to append RFID tags

### ISSUE THREAD

**Issue by khuemann** [pumpingstationone/WA2AD#11]
I was testing with Testy McTestface and added a RFID tag to this account; however, I noticed that there were three numbers associated with the account in AD. It appears WA2AD appends and does not delete the old RFID numbers.

This was in WA:
0010816133

This was in AD:
['0010816133', '7890321', '00001234']    111testuser              Testy        McTestface           nottheoriginalemail@gmail.com  1601-01-01 00:00:00+00:00

**Comment by tachoknight** [comment]
Fixed in [this commit](https://github.com/pumpingstationone/WA2AD/commit/cf04ed7a4b7a3df641b19721e83216410f95a4ba). Will be labeled 1.5.1
