### ISSUE TITLE
userPrincipalName not being set (only sAMAccountName)

### ISSUE THREAD

**Issue by dogshapedangel** [pumpingstationone/WA2AD#3]
It appears that the tool is only setting `sAMAccountName`. Both `sAMAccountName` and `userPrincipalName` should be set for full functionality

`userPrincipalName` has a character limit of 256 and takes the format `[username]@[domain].[TLD]` for example - user@pumpingstationone.org

`sAMAccountName` has a character limit of 20 and takes the format `[username]` eg - user. Windows normally truncates this automatically when manually creating a user. From the error we're getting, it looks like we'll need to send AD an already truncated username for this attribute.

**Comment by tachoknight** [comment]
Fixed in [4153f788](https://github.com/pumpingstationone/WA2AD/commit/4153f788fe07961214dd8c66bf41443e821385e4)
