### ISSUE TITLE
Random error "object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by dogshapedangel** [pumpingstationone/WA2AD#4]
Appears to be randomly throwing the following error. 

`PS C:\WA2AD> .\WA2AD.exe
Starting...
Starting to get the data from Wild Apricot...
Finished getting the data from Wild Apricot...
...and we have data to work with.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at WA2AD.Program..ctor() in C:\Users\Mituna\Source\Repos\pumpingstationone\WA2AD\Program.cs:line 18
   at WA2AD.Program.Main(String[] args) in C:\Users\Mituna\Source\Repos\pumpingstationone\WA2AD\Program.cs:line 31`

**Comment by tachoknight** [comment]
Yeah this is a weird one; it throws this error, but then the next go it works fine. The exception handling in [4153f788](https://github.com/pumpingstationone/WA2AD/commit/4153f788fe07961214dd8c66bf41443e821385e4) may not exactly help, but at least if the app doesn't run this time, it'll run the next time.

**Comment by tachoknight** [comment]
This was due to the person in WA not being a member, just a contact. This is fixed [in this commit](https://github.com/pumpingstationone/WA2AD/commit/f5817b0d175bfc04b851da1296e55e7ecd4f5ad2).
