### ISSUE TITLE
Eliminate embedded credentials requirement 

### ISSUE THREAD

**Issue by dogshapedangel** [pumpingstationone/WA2AD#7]
Since the application can run as the service account that's been granted appropriate permissions in AD, can we eliminate the need for embedded account credentials? Can it just run all AD calls as the user the code is running under?

**Comment by dogshapedangel** [comment]
This would definitely streamline deployment as well

**Comment by dogshapedangel** [comment]
Actually, I just realized you're also requiring a DC to be specified... do we need to do that for AD? can't it just hit up the pumpingstationone.org domain and reach whatever available DC responds? (and yes it is hosted on DC1 at the moment but we can make a machine explicitly for Windows based connectors to increase redundancy)

**Comment by tachoknight** [comment]
This was a consequence of developing the app from a machine not on the network. I will change it to work this way:

1. Check if there's a settings file, and if there is, use that
2. If there's no settings file, attempt to use the domain and user that the program is currently running under

**Comment by tachoknight** [comment]
Fixed in [this commit](https://github.com/pumpingstationone/WA2AD/commit/f5817b0d175bfc04b851da1296e55e7ecd4f5ad2)
